version: '3.8'
services:
  mongoLimitChecker:
    image: mongolimit
    volumes:
      - /media/kodiya/hard1/mongo_Limti_Check_Log:/log
    command: [ "node", "mongoLimitChecker.js" ]
    environment:
      MONGO_SERVER_DB_URI: "your uri"
      LOG_FILE_PATH: "your log path"
      CONF_ID: "your conf id"
      COLL_IDENTIFY_VALUE: "your coll identify value"
      DB_NAME: "your db name"
